release:
  draft: true
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd
    binary: http-file-server
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64
archives:
  - name_template: "http-file-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip  
    replacements:
      darwin: osx
      linux: linux
      windows: windows
      386: x86_32
      amd64: x86_64
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
